language: node_js
node_js:
- '0.12'
- '0.10'
sudo: false
before_script:
- npm install
deploy:
  provider: npm
  email: andrewn@datatribe.net
  api_key:
    secure: I6Xl3psEn/yJ24RKTYpQLRpNQYhVApfw+BH76Hu2FhUTiTmDq3fjxnGPCUfPoF3YgYkE6evTPhh28Mybniuti1EsSRvTzpsY0vPVQCHkyHwu0VxPJ+DXduz71D7ASEIJM0ixH+xJ6vet4+PW7PSb8SDFV6YfeJq1SV8dlRicNFo=
  on:
    tags: true
    node: '0.10'
env:
  global:
  - secure: C2Qt8INQLZqRLGYH6st+GEp+8SVIDH/JQ4P1rURjZo14Nk3hLNGvymJAQPpMZwKMZ47k4MvxyUgoXWk3VW4OgdOxiVKfFah7YBMs8hFCIM8xu0zcK/wCgAwM0WuPAw5cqI+uSmVhEKQVNyaOAkCaa8vljg2ZwA1knmzbIIV38YE=
  - secure: eQ4GGY/fKVsEx6ma/73yCA0XtKsuLBE8UqOH+SXlghhm+X78ZAIurMWUlD2HzcXdwVDo4iDKUJT44GAsesHape/8vzrMIUcpRdggZVi8FCEdjCI9KaEumPxgqQx3XROSuzW6QewM/7MoNuL0bAjpH60zTEJgI8XIvviQLjzkqEM=
